# Generated by Django 5.1.5 on 2025-01-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_name", models.CharField(max_length=255)),
                ("bill_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "transaction_screenshot_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
