# Generated by Django 5.1.3 on 2025-01-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Cr', 'Credit'), ('Dr', 'Debit')], default='Cr', max_length=2),
            preserve_default=False,
        ),
    ]
