# Generated by Django 5.1.3 on 2025-01-27 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0002_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_happened', '-last_updated'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_happened',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
